### PR TITLE
Document supported and unsupported recursive referencing

### PR DESCRIPTION
**Pull request by kylef**

### CODE REVIEW

**Comment by pksunkara** [comment]
IIRC a few circular mixins are not supported. @w-vi will have a better idea. We need to add that.

**Comment by kylef** [comment]
@pksunkara I don't see a case where it is supported via mixins during my own testing. My changes state it does not work in Type Inheritance (section 5) where Mixins are a subsection of Type Inheritance thus I stated this is not supported for Mixins.

**Comment by w-vi** [comment]
So I looked at the fixtures and code and the way it is described in the spec is good.

**Comment by pksunkara** [comment]
👍

**Pull request merged**
