### PR TITLE
adding `null` primitive type

### PR DESCRIPTION
**Pull request by obihann**
After the discussion on issue #26 I felt it would be a good idea to add the primitive type `null`.

### CODE REVIEW

**Comment by zdne** [comment]
Hey @obihann ! Appreciate your effort but I would like to wait with this PR until the discussion in https://github.com/apiaryio/mson/issues/26#issuecomment-133029966 is closed. Please lets discuss there, what is the best possible solution and why. 

Thanks!

**Comment by obihann** [comment]
@zdne Thanks for the reply. I understand wanting to wait till the discussion is over however what I take from that discussion is two things 1) their is no implementation of null as a primitive type, which is critical because null is a valid JSON type, and 2) how will we allow fields to be optionally null. 

The far larger issue is 2, and I purposely avoided addressing that as to allow the conversation to solve that for me.

Either way, let me know if I can help.

**Comment by zdne** [comment]
@obihann 

Thanks! As discussed in #26 I am hesitant to introduce `null` as a type. With that, however, I totally see the need to address the following: 

1. allow a value of any type to be `null` (not set) 
2. allow a value of any type to be a default empty value (`""`, `[]`, `{}`, `0`)

Let's discuss it in #26 ...

**Comment by obihann** [comment]
@zdne Just to keep this thread up to speed with my other comments in #26 I do agree with you on 1 and 2. Well carry this on in their now.

**Review by Duc56789 — COMMENTED** [review]
Ggg

**Pull request closed without merging**
